### ISSUE TITLE
Can't compile using gcc version 11.1.0

### ISSUE THREAD

**Issue by OpenUp12** [mav8557/Father#6]
The code can't be compile using gcc version 11.

```
gcc -Wall -fPIC -shared -D_GNU_SOURCE -o bin/access.o src/access.c -c
src/access.c: In function ‘access’:
src/access.c:23:18: error: ‘_STAT_VER’ undeclared (first use in this function)
   23 |         __lxstat(_STAT_VER, pathname, &s_buf);
      |                  ^~~~~~~~~
src/access.c:23:18: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:16: bin/access.o] Error 1
```

**Comment by mav8557** [comment]
It looks like some definitions flew out from under me! I also ran into this issue, as it appears _STAT_VER is no longer defined for some systems. I have pushed an update, so pull the latest version and let me know if that still doesn't work.
